FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port (change if needed)
EXPOSE 8001

# Run FastAPI with Uvicorn

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]

